### PR TITLE
Fix the update of multi-level nested options

### LINKED ISSUE #241: DxChart - Nested items cannot be updated
The DevExtreme Angular package's version is 16.2.1-alpha.3
 
Reproduced in [example](http://plnkr.co/edit/qnBHNGlllczpiV6pyXzo?p=preview).
To reproduce the problem, select the 'fullStackedArea' value in DxSelectBox and take a look at the console.

### PR DESCRIPTION
**Pull request by anna-zhernovkova**
Close #241

### CODE REVIEW

File: src/core/nested-option.ts [hunk 1]
```diff
@@ -6,13 +6,23 @@ export interface INestedOptionContainer {
...
     private _collectionContainerImpl: ICollectionNestedOptionContainer;
     protected _initialOptions = {};
 
-    protected _updateBaseOptionPath() {
-        this._baseOptionPath = this._hostOptionPath + this._optionPath + '.';
+    protected _getFullOptionPath(optionPath) {
+        let element: any = this,
+            fullPath: string = optionPath;
+
+        while (element && element._pnoh && element._pnoh._optionPath !== '') {
```
Comment (kvet) [inline src/core/nested-option.ts]: Why are you use private members? Seems that you should not iterate thought parents this way. Maybe it is better to use parent's `getFullOptionPath` instead of while loop.
