### PR TITLE
Fix ControlValueAccessor interface implementation

### LINKED ISSUE #224: Reactive Forms - FormControl.disable() not being applied
Hi,

I am unable to use the disable() method of a FormControl to control the enabled/disabled state of the devextreme editor.

I have created the following plunker to demonstrate the issue. 
[http://plnkr.co/edit/zgvcWTm9M4BrUvroUV7C?p=preview](http://plnkr.co/edit/zgvcWTm9M4BrUvroUV7C?p=preview)

Regards, Jon.

### PR DESCRIPTION
**Pull request by Aden-git**
Fix #224

### CODE REVIEW

File: examples/app/app.component.ts [hunk 1]
```diff
@@ -169,6 +169,15 @@ export class AppComponent implements OnInit {
     callNumber(number) {
         alert(number + ' is being called...');
     }
+    toggleFormConsrolsState(e) {
```
Comment (ovchinnikov) [inline examples/app/app.component.ts]: This should be tested
